name: Compile, Build and Deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Compile, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Compile
        run: flutter pub get
      - name: Build
        working-directory: ./example
        run: flutter build web --release
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TOKEN_SELECT2DOT1 }}
          publish_dir: ./example/build/web
          cname: select2dot1.site

      
